pipeline {
    agent "devops-jenkins-slave" 

    tools {
        // This is the variable name "MAVEN384" configured in the Jenkins Global Tool Configuration under Add maven.
        maven "MAVEN384"
    }

    stages {
        stage('Compile') {
            steps {
                // Get some code from a GitHub repository
                git 'https://github.com/tektutor/spring-ms.git'

                // Compile the application source code 
                sh "mvn clean compile"
            }
        }
        stage('Unit Test') {
            steps {
                // Get some code from a GitHub repository
                git 'https://github.com/tektutor/spring-ms.git'

		//Perform unit test
                sh "mvn test"
            }
        }
        stage('Package') {
            steps {
                // Get some code from a GitHub repository
                git 'https://github.com/tektutor/spring-ms.git'

                // Create jar file 
                sh "mvn package"
            }
        }
        stage('Install') {
            steps {
                // Get some code from a GitHub repository
                git 'https://github.com/tektutor/spring-ms.git'

		// Install the artifacts into local maven repository
                sh "mvn install"
            }
        }
    }
}
